apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: f9f2b8d9588e4dbfa490bf80c35654e96fede136
    app.openshift.io/vcs-uri: https://github.com/fbh112/e2e_nextjs
  labels:
    app.kubernetes.io/instance: nextjs-sample-app
    app.kubernetes.io/name: nextjs-sample-app
  name: nextjs-sample-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: nextjs-sample-app
    app.kubernetes.io/name: nextjs-sample-app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: f9f2b8d9588e4dbfa490bf80c35654e96fede136
    app.openshift.io/vcs-uri: https://github.com/fbh112/e2e_nextjs
  labels:
    app.kubernetes.io/instance: nextjs-sample-app
    app.kubernetes.io/name: nextjs-sample-app
    app.openshift.io/runtime: js
  name: nextjs-sample-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: nextjs-sample-app
      app.kubernetes.io/name: nextjs-sample-app
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: f9f2b8d9588e4dbfa490bf80c35654e96fede136
        app.openshift.io/vcs-uri: https://github.com/fbh112/e2e_nextjs
      labels:
        app.kubernetes.io/instance: nextjs-sample-app
        app.kubernetes.io/name: nextjs-sample-app
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/ting_wu/e2e_nextjs:f9f2b8d9588e4dbfa490bf80c35654e96fede136
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: nextjs-sample-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: f9f2b8d9588e4dbfa490bf80c35654e96fede136
    app.openshift.io/vcs-uri: https://github.com/fbh112/e2e_nextjs
  labels:
    app.kubernetes.io/instance: nextjs-sample-app
    app.kubernetes.io/name: nextjs-sample-app
  name: nextjs-sample-app
spec:
  port:
    targetPort: 3000
  tls:
    termination: edge
  to:
    kind: Service
    name: nextjs-sample-app
    weight: 100
  wildcardPolicy: None
