apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 1a72e2f07f3d64c6957fdc2a4ccd5161fa9f158c
    app.openshift.io/vcs-uri: https://github.com/fbh112/e2e_project.git
  labels:
    app.kubernetes.io/instance: funfact-app
    app.kubernetes.io/name: funfact-app
  name: funfact-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: funfact-app
    app.kubernetes.io/name: funfact-app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 1a72e2f07f3d64c6957fdc2a4ccd5161fa9f158c
    app.openshift.io/vcs-uri: https://github.com/fbh112/e2e_project.git
  labels:
    app.kubernetes.io/instance: funfact-app
    app.kubernetes.io/name: funfact-app
    app.openshift.io/runtime: js
  name: funfact-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: funfact-app
      app.kubernetes.io/name: funfact-app
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 1a72e2f07f3d64c6957fdc2a4ccd5161fa9f158c
        app.openshift.io/vcs-uri: https://github.com/fbh112/e2e_project.git
      labels:
        app.kubernetes.io/instance: funfact-app
        app.kubernetes.io/name: funfact-app
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/ting_wu/funfact-app:1a72e2f07f3d64c6957fdc2a4ccd5161fa9f158c
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: funfact-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 1a72e2f07f3d64c6957fdc2a4ccd5161fa9f158c
    app.openshift.io/vcs-uri: https://github.com/fbh112/e2e_project.git
  labels:
    app.kubernetes.io/instance: funfact-app
    app.kubernetes.io/name: funfact-app
  name: funfact-app
spec:
  port:
    targetPort: 3000
  tls:
    termination: edge
  to:
    kind: Service
    name: funfact-app
    weight: 100
  wildcardPolicy: None
